[versions]
compose = "1.4.0-alpha3"
compose-compiler = "1.4.0-alpha02"
lifecycle = "2.5.1"
kotlin = "1.7.20"
ksp = "1.7.20-1.0.8"
agp = "7.4"

[libraries]
compose-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
compose-activity = { module = "androidx.activity:activity-compose", version = "1.7.0-alpha02" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version = "compose" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-fonts = { module = "androidx.compose.ui:ui-text-google-fonts", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "compose" }
compose-ui-viewbinding = { module = "androidx.compose.ui:ui-viewbinding", version.ref = "compose" }

coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.6.4" }

datastore = { module = "androidx.datastore:datastore-preferences", version = "1.0.0" }

lifecycle-compiler = { module = "androidx.lifecycle:lifecycle-compiler", version.ref = "lifecycle" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }

modo = { module = "com.github.terrakok:modo-compose", version = "0.7.1" }

[bundles]
compose = [
    "compose-animation",
    "compose-activity",
    "compose-foundation",
    "compose-layout",
    "compose-material",
    "compose-runtime",
    "compose-ui",
    "compose-ui-fonts",
    "compose-ui-tooling",
    "compose-ui-tooling-preview",
    "compose-ui-util",
    "compose-ui-viewbinding"
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
